package interfaceGraphique;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import projetAgent.*;

public class InterfaceRecherche extends javax.swing.JFrame {

	/**
	 * Creates new form FormulaireClient
	 */
	private ClientBehavior clientBehavior;
	private InterfaceAchat interfaceAchat;
	private InterfaceProduit interfaceProduit;
	private ClientAgent clientAgent;

	public InterfaceRecherche() {
		clientAgent = new ClientAgent();
		clientBehavior = new ClientBehavior();
		interfaceAchat = new InterfaceAchat();
		interfaceProduit = new InterfaceProduit();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		textReference = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		textCategory = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		textNom = new javax.swing.JTextField();
		rechercheButton = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		textTags = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Recherche de produit");

		jLabel2.setText("Par référence");

		jLabel3.setText("Par catégorie");

		jLabel4.setText("Par nom");

		rechercheButton.setText("Recherche");
		rechercheButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rechercheButtonActionPerformed(evt);
			}
		});

		jLabel5.setText("Tags");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabel1))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(32, 32,
																		32)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel2)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										textReference,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										150,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel3)
																												.addComponent(
																														jLabel4)
																												.addComponent(
																														jLabel5))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														textCategory)
																												.addComponent(
																														textNom)
																												.addComponent(
																														textTags)))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(156,
																		156,
																		156)
																.addComponent(
																		rechercheButton)))
								.addContainerGap(142, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														textReference,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														textCategory,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														textNom,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														textTags,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										43, Short.MAX_VALUE)
								.addComponent(rechercheButton)
								.addGap(57, 57, 57)));

		pack();
	}// </editor-fold>

	private void rechercheButtonActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		/* Recupere les champs textes */
		String reference = textReference.getText();
		String category = textCategory.getText();
		String nom = textNom.getText();
		String tags = textTags.getText();
		System.out.println("texte : " + textReference.getText());
		if (!reference.equals("")) {
			clientBehavior.askProductPriceWithSeller(reference);
			ArrayList<Message> lMessage = clientBehavior
					.receivePriceProductFromSeller();
			interfaceAchat.setListeMessage(lMessage);
			for (int i = 0; i < lMessage.size(); i++) {
				lMessage.get(i).setReference(reference);
				lMessage.get(i).setType("Vendeur");
				interfaceAchat.addRowInJTable(lMessage.get(i));

			}
			if(lMessage.size() == 0){
				JOptionPane.showMessageDialog(this, "Il n'y a aucun produit qui correspond à votre recherche");
			}else{
				interfaceAchat.lancer();
			}
		} else {
			String message = "";

			if (!category.equals("") && !nom.equals("")  && !tags.equals("") ) {
				message = category + "," + nom + "," + tags;
			} else {
				if (!textCategory.getText().equals("")) {
					message = category + ",null,null";
				}

				if (!textNom.getText().equals("")) {
					message = "null," + nom + ",null";
				}

				if (!textTags.getText().equals("")) {
					message = "null,null," + tags;
				}
			}
			System.out.println(message);
			ArrayList<Message> listeCopy = new ArrayList<>();
			clientBehavior.askProductWithCriteria(message);
			ArrayList<ArrayList<Message>> list_message = clientBehavior.receiveListOfProduct();
			for (int i = 0; i < list_message.size(); i++) {
				for (int j = 0; j < list_message.get(i).size(); j++) {
					listeCopy.add(list_message.get(i).get(j));
				}
			}
			for(int i = 0 ; i < listeCopy.size() ; i++){
				interfaceProduit.addRowInJTable(listeCopy.get(i));
			}
			if(listeCopy.size() == 0){
				JOptionPane.showMessageDialog(this, "Il n'y a aucun produit qui correspond à votre recherche");
			}else{
				interfaceProduit.setArrayList(listeCopy);
				interfaceProduit.lancer();
			}
			
		}
	}
	

	/**
	 * @param args
	 *            the command line arguments
	 */
	public void lancerInterface() {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					InterfaceRecherche.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					InterfaceRecherche.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					InterfaceRecherche.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					InterfaceRecherche.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		this.setTitle("Recherche de produit");
		this.setVisible(true);
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JButton rechercheButton;
	private javax.swing.JTextField textCategory;
	private javax.swing.JTextField textNom;
	private javax.swing.JTextField textReference;
	private javax.swing.JTextField textTags;
	// End of variables declaration
}