package interfaceGraphique;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import projetAgent.ClientBehavior;
import projetAgent.Message;

/**
 *
 * @author Phongphet
 */
public class InterfaceAchat extends javax.swing.JFrame {

    /**
     * Creates new form FormulaireResultatRecherche
     */
	private ClientBehavior clienBehavior;
	private ArrayList<Message> listeMessage;
	
    public InterfaceAchat() {
    	clienBehavior = new ClientBehavior();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Résultat de la recherche");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Référence", "Produit", "Prix", "Vendeur", "Type"
            }
        ));
 
        jScrollPane1.setViewportView(jTable1);

        jCheckBox1.setText("Comparer le produit sélectionné chez les fournisseurs");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jCheckBox1ActionPerformed(evt);
            }
        });
        
        jButton1.setText("Acheter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jCheckBox1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

                                        
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:    	
    	clienBehavior.askProductWithSupplier(listeMessage.get(0).getReference());
    	ArrayList<Message> lMessage = clienBehavior.receivePriceProductFromSupplier();
		for (int i = 0; i < lMessage.size(); i++) {
			Message m = lMessage.get(i);
			m.setReference(listeMessage.get(0).getReference());
			m.setType("Fournisseur");
			this.addRowInJTable(lMessage.get(i));
		}
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int indice = jTable1.getSelectedRow();
        System.out.println("Indice : "+indice);
        if(indice != -1){
        	if(listeMessage.get(indice).getType().equals("vendeur")){
        		clienBehavior.askToBuyProductWithSeller(listeMessage.get(indice).getReference());
            	Message mess = clienBehavior.receiveResponseFromSeller();
            	if(mess != null){
            		JOptionPane.showConfirmDialog(this, "Votre achat est valide");
            	}
        	}else{
        		clienBehavior.askToBuyProductWithSupplier(listeMessage.get(indice).getReference());
            	Message mess = clienBehavior.receiveResponseFromSupplier();
            	if(mess != null){
            		JOptionPane.showConfirmDialog(this, "Votre achat est valide");
            	}
        	}
        	
        }
    }   
    
    public void setListeMessage(ArrayList<Message> listeMessage){
    	this.listeMessage = listeMessage;
    }
    
    public void addRowInJTable(Message message){
    	DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    	model.addRow(new Object[]{message.getReference(), message.getCategorie(), message.getPrix(), message.getVendeur(), message.getType()});
    }

    /**
     * @param args the command line arguments
     */
    public void lancer() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceAchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        this.setVisible(true);
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}

